# Generated by Django 3.2.4 on 2021-08-21 21:36

from django.db import migrations, models
import django.db.models.deletion
import rooms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomTypes',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='name')),
                ('image', models.ImageField(upload_to='room pics')),
                ('price', models.IntegerField(validators=[rooms.models.is_pos], verbose_name='price')),
                ('size', models.IntegerField(validators=[rooms.models.is_pos], verbose_name='Size')),
                ('beds', models.SmallIntegerField(validators=[rooms.models.is_pos], verbose_name='beds')),
                ('count', models.IntegerField(validators=[rooms.models.is_pos], verbose_name='count')),
                ('max_guests', models.IntegerField(validators=[rooms.models.is_pos], verbose_name='max guests')),
                ('desc', models.TextField(verbose_name='Description')),
                ('offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='offers.offer')),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.SmallIntegerField(validators=[rooms.models.is_pos])),
                ('state', models.CharField(choices=[('1', 'Under maintenance'), ('2', 'Inhabited'), ('3', 'Empty')], default='3', max_length=1)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.roomtypes')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.rooms')),
            ],
        ),
    ]
