# Generated by Django 3.2.4 on 2021-08-21 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reservation.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp_Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=13, unique=True)),
                ('start_date', models.DateTimeField(help_text='From date')),
                ('end_date', models.DateTimeField(help_text='To date')),
                ('active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.customers')),
                ('room_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.roomtypes')),
            ],
            options={
                'ordering': ['active'],
            },
        ),
        migrations.CreateModel(
            name='Perma_Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('bill', models.IntegerField(validators=[reservation.models.is_pos])),
                ('active', models.BooleanField(default=True)),
                ('num_passport', models.IntegerField(default=0, validators=[reservation.models.is_pos])),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rooms.rooms')),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.visitors')),
            ],
            options={
                'ordering': ['active'],
            },
        ),
    ]
