# Generated by Django 3.2.4 on 2021-08-25 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20210823_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perma_reservation',
            old_name='num_passport',
            new_name='number',
        ),
    ]
