# Generated by Django 3.2.4 on 2021-08-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_rename_num_passport_perma_reservation_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perma_reservation',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='perma_reservation',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
